
FROM python:3.11-slim

WORKDIR /app


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY ui ./ui


ENV API_BASE_URL="http://localhost:8000"
ENV PYTHONUNBUFFERED=1


EXPOSE 8501


CMD ["bash", "-lc", "streamlit run ui/app.py --server.port 8501 --server.address 0.0.0.0"]
